window.animalAssets = {
  meta: {
    activeSet: "stitch_child_friendly_animal_asset_library",
    note: "Central animal asset registry. Current sources are locally processed transparent PNGs derived from stitch_child_friendly_animal_asset_library.",
  },
  species: {
    persian: {
      label: "波斯猫",
      imageUrl: "./assets/animal-library/persian.png",
      source: "stitch_child_friendly_animal_asset_library",
      license: "local workspace asset",
      fallbackClass: "persian",
    },
    garfield: {
      label: "加菲猫",
      imageUrl: "./assets/animal-library/garfield.png",
      source: "stitch_child_friendly_animal_asset_library",
      license: "local workspace asset",
      fallbackClass: "garfield",
    },
    shortEar: {
      label: "短耳猫",
      imageUrl: "./assets/animal-library/shortEar.png",
      source: "stitch_child_friendly_animal_asset_library",
      license: "local workspace asset",
      fallbackClass: "shortEar",
    },
    bulldog: {
      label: "斗牛犬",
      imageUrl: "./assets/animal-library/bulldog.png",
      source: "stitch_child_friendly_animal_asset_library",
      license: "local workspace asset",
      fallbackClass: "bulldog",
    },
    golden: {
      label: "金毛犬",
      imageUrl: "./assets/animal-library/golden.png",
      source: "stitch_child_friendly_animal_asset_library",
      license: "local workspace asset",
      fallbackClass: "golden",
    },
    teddy: {
      label: "泰迪",
      imageUrl: "./assets/animal-library/teddy.png",
      source: "stitch_child_friendly_animal_asset_library",
      license: "local workspace asset",
      fallbackClass: "teddy",
    },
    triceratops: {
      label: "三角龙",
      imageUrl: "./assets/animal-library/triceratops.png",
      source: "stitch_child_friendly_animal_asset_library",
      license: "local workspace asset",
      fallbackClass: "triceratops",
    },
    stegosaurus: {
      label: "剑龙",
      imageUrl: "./assets/animal-library/stegosaurus.png",
      source: "stitch_child_friendly_animal_asset_library",
      license: "local workspace asset",
      fallbackClass: "stegosaurus",
    },
    ankylosaurus: {
      label: "甲龙",
      imageUrl: "./assets/animal-library/ankylosaurus.png",
      source: "stitch_child_friendly_animal_asset_library",
      license: "local workspace asset",
      fallbackClass: "ankylosaurus",
    },
    trex: {
      label: "霸王龙",
      imageUrl: "./assets/animal-library/trex.png",
      source: "stitch_child_friendly_animal_asset_library",
      license: "local workspace asset",
      fallbackClass: "trex",
    },
    giga: {
      label: "迅猛龙",
      imageUrl: "./assets/animal-library/giga.png",
      source: "stitch_child_friendly_animal_asset_library",
      license: "local workspace asset",
      fallbackClass: "giga",
    },
    indominus: {
      label: "食肉牛龙",
      imageUrl: "./assets/animal-library/indominus.png",
      source: "stitch_child_friendly_animal_asset_library",
      license: "local workspace asset",
      fallbackClass: "indominus",
    },
  },
};
